packages:
  - "apps/*"
  - "packages/*"

catalog:
  # TypeScript
  typescript: "5.9.3"
  "@types/node": "^22.10.7"

  # Linting & Formatting
  eslint: "^10.0.0"
  prettier: "^3.8.0"
  globals: "^17.3.0"

  # Svelte ecosystem
  svelte: "^5.47.1"
  "@sveltejs/kit": "^2.50.2"
  "@sveltejs/vite-plugin-svelte": "^6.2.1"
  prettier-plugin-svelte: "^3.4.0"
  svelte-check: "^4.3.4"
  vite: "^7.2.6"
