packages:
  - "apps/*"
  - "packages/*"

catalog:
  # TypeScript
  typescript: "5.9.3"
  "@types/node": "^22.10.7"

  # Linting & Formatting
  eslint: "^9.39.0"
  "@eslint/compat": "^1.4.0"
  prettier: "^3.8.0"

  # Svelte ecosystem
  svelte: "^5.51.2"
  "@sveltejs/kit": "^2.52.0"
  "@sveltejs/vite-plugin-svelte": "^6.2.1"
  prettier-plugin-svelte: "^3.4.0"
  svelte-check: "^4.4.0"
  vite: "^7.2.6"
